/* Automatically generated by wasm2c */
#ifndef WASM_H_GENERATED_
#define WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_wasm {
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_wasm;

void wasm2c_wasm_instantiate(w2c_wasm*);
void wasm2c_wasm_free(w2c_wasm*);
wasm_rt_func_type_t wasm2c_wasm_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'memory' */
wasm_rt_memory_t* w2c_wasm_memory(w2c_wasm* instance);

/* export: 'wasm_deepseek_hash_v1' */
void w2c_wasm_wasm_deepseek_hash_v1(w2c_wasm*, u32, u32, u32);

/* export: 'wasm_solve' */
void w2c_wasm_wasm_solve(w2c_wasm*, u32, u32, u32, u32, u32, f64);

/* export: '__wbindgen_add_to_stack_pointer' */
u32 w2c_wasm_0x5F_wbindgen_add_to_stack_pointer(w2c_wasm*, u32);

/* export: '__wbindgen_export_0' */
u32 w2c_wasm_0x5F_wbindgen_export_0(w2c_wasm*, u32, u32);

/* export: '__wbindgen_export_1' */
u32 w2c_wasm_0x5F_wbindgen_export_1(w2c_wasm*, u32, u32, u32, u32);

/* export: '__wbindgen_export_2' */
void w2c_wasm_0x5F_wbindgen_export_2(w2c_wasm*, u32, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* WASM_H_GENERATED_ */
